/***** PRODUCTS *****/
export const SET_PRODUCTS_DATA = "SET_PRODUCTS_DATA";
export const FETCH_PRODUCTS = "FETCH_PRODUCTS";
export const ADD_PRODUCTS_CATEGORY_FILTER = "ADD_PRODUCTS_CATEGORY_FILTER";
export const ADD_PRODUCTS_KEYWORD_FILTER = "ADD_PRODUCTS_KEYWORD_FILTER";
export const ADD_PRODUCTS_SORT_FILTER = "ADD_PRODUCTS_SORT_FILTER";
export const ADD_PRODUCTS_PER_PAGE_FILTER = "ADD_PRODUCTS_PER_PAGE_FILTER";
export const RESET_PRODUCTS_FILTER = "RESET_PRODUCTS_FILTER";
export const SET_PRODUCTS_CURRENT_PAGE = "SET_PRODUCTS_CURRENT_PAGE";

/***** DEALERS *****/
export const SET_DEALERS_DATA = "SET_DEALERS_DATA";
export const FETCH_DEALERS = "FETCH_DEALERS";
export const ADD_DEALERS_CATEGORY_FILTER = "ADD_DEALERS_CATEGORY_FILTER";
export const ADD_DEALERS_KEYWORD_FILTER = "ADD_DEALERS_KEYWORD_FILTER";
export const ADD_DEALERS_SORT_FILTER = "ADD_DEALERS_SORT_FILTER";
export const ADD_DEALERS_PER_PAGE_FILTER = "ADD_DEALERS_PER_PAGE_FILTER";
export const RESET_DEALERS_FILTER = "RESET_DEALERS_FILTER";
export const SET_DEALERS_CURRENT_PAGE = "SET_DEALERS_CURRENT_PAGE";
export const SET_DEALERS_CATEGORIES = "SET_DEALERS_CATEGORIES";