export const SET_PRODUCTS_DATA = "SET_PRODUCTS_DATA";
export const FETCH_PRODUCTS = "FETCH_PRODUCTS";

/***** FILTER *****/
export const ADD_CATEGORY_FILTER = "ADD_CATEGORY_FILTER";
export const ADD_KEYWORD_FILTER = "ADD_KEYWORD_FILTER";
export const ADD_SORT_FILTER = "ADD_SORT_FILTER";
export const ADD_PER_PAGE_FILTER = "ADD_PER_PAGE_FILTER";
export const RESET_FILTER = "RESET_FILTER";
export const SET_CURRENT_PAGE = "SET_CURRENT_PAGE";